### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by arschles** [arschles/go-in-5-minutes#14]
solve these problems: http://whipperstacker.com/2015/10/05/3-trivial-concurrency-exercises-for-the-confused-newbie-gopher/

- [x] Exercise 1: The Daily Walk (#52)
- [x] Exercise 2: Eating Tapas (#54)
- [x] Exercise 3: Internet Café (#84)

**Comment by carlisia** [comment]
:+1:

**Comment by varun06** [comment]
:+1:

**Comment by ramirovjr** [comment]
:+1:

**Comment by fud** [comment]
:+1: :zap:

**Comment by digitalcraftsman** [comment]
:+1:

**Comment by arschles** [comment]
Ok all - the three problems are now solved in screencasts:

1. The Daily Walk: http://www.goin5minutes.com/screencast/episode_10_concurrency_the_daily_walk/
2. Eating Tapas: http://www.goin5minutes.com/screencast/episode_12_concurrency_eating_tapas/
3. Internet Cafe: http://www.goin5minutes.com/screencast/episode_15_internet_cafe/
  - This problem has some interesting challenges. An extended screencast that outlines them is up at https://gum.co/gifm-x-15
